name: Build & Deploy Vue
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: 安装依赖
        run: npm install
      - name: 打包Vue项目
        run: npm run build
      - name: 上传打包产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
